name: github-tag

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - $default-branch

jobs:
  github-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: CHANGELOG
        run: |
          echo "${{ steps.tag_version.outputs.changelog }}" >> changelog.md
          
      - name: Archive changelog as artifact
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: changelog.md
          retention-days: 2
