name: release-only

on:
  workflow_dispatch:
    branches:
      - $default-branch
    inputs:
      next_version:
        description: 'Next version (v1.2.3)'
        required: true
      release_body:
        description: 'Release description body'

jobs:
  release-only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # will this create the release tag when it doesn't exist?
      - uses: ncipollo/release-action@d95f7f9bad25c349a7d18578c773a3277b6936e4 # v1.8.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.next_version }}
          allowUpdates: true
        # artifacts: 'artifact.zip'
          body: ${{ github.event.inputs.release_body }}
