name: release-only

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - $default-branch

jobs:
  release-only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: get_version
        run: echo "::set-output name=next_version::v1.3.3"

      # will this create the release tag when it doesn't exist?
      - uses: softprops/action-gh-release@91409e712cf565ce9eff10c87a8d1b11b81757ae # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.next_version }}
          body: |
            These are all the things I would like to note with this release. ${{ steps.get_version.outputs.next_version }}
