name: github-tag

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - $default-branch

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: marvinpinto/action-automatic-releases@8d9ddb2546e687f72855285d2719a11709cea6d0 # v1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            README.md
